@echo off
Rem Takes each file from the expectedOuputs directory and compares them with the output files
Rem generated by the program in the outputs directory.

if not exist "tests\results" mkdir "tests\results"

if exist "tests\results\results.log" del "tests\results\results.log"
@echo Test at %date% %time% >> "tests\results\results.log"

FOR %%G in ("tests/expectedOutputs/*.txt") do (
    echo Checking outputs of test: %%G
    @echo off
    echo %%G TEST RESULT: >> "tests\results\results.log"
    echo n | comp "tests\outputs\%%G" "tests\expectedOutputs\%%G" /L >> "tests\results\results.log"
)